config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'application#home'

  get 'about/', to: 'application#about', as: 'about'
  
  resources :events

  resources :tasks, except: [:index]
  get '/add_task/:id', to: 'tasks#add_task', as: 'add_task'
  post '/add_task/:id', to: 'tasks#add_task'
  get '/complete_task/:id', to: 'tasks#complete_task', as: 'complete_task'
  post '/complete_task/:id', to: 'tasks#complete_task'
  get '/remove_task/:id', to: 'tasks#remove_task', as: 'remove_task'
  post '/remove_task/:id', to: 'tasks#remove_task'

  resources :users, except: [:index]

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  delete '/signout', to: 'sessions#destroy'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id            :integer          not null, primary key
#  title         :string
#  event_id      :integer
#  location_id   :integer
#  task_location :string
#  description   :text
#  priority      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Task < ApplicationRecord
  belongs_to :event
  belongs_to :location
  belongs_to :user, optional: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in
  before_action :find_task, only: [:show, :edit, :update, :destroy, :add_task, :complete_task, :remove_task, :validate_event]

  def new
    @task = Task.new
    @event = Event.find(params[:event_id])
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "You Made A Task"
      redirect_to task_path(@task)
    else
      flash[:error] = "Making A Task Didn't Work"
      # render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = "Task Changes Were Applied"
      redirect_to task_path(@task)
    else
      flash[:error] = "Task Updated Failed Yo"
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Destroyed Dat Task"
    redirect_to root_path
  end

  def add_task
    @task.update(user: current_user, status: "in progress")
    redirect_to event_path(@task.event)
  end

  # def add_task
  #   if validate_event
  #     @task.update(user: current_user, status: "in progress")
  #     redirect_to event_path(@task.event)
  #   else
  #     flash[:error] = "This event conflicts with your current schedule!"
  #     redirect_to task_path(@task)
  #   end
  # end

  # def validate_event
  #   current_user.events.each do |e|
  #     if e.end_date < @task.event.start_date || @task.event.end_date < e.start_date
  #       puts true
  #     end
  #   end
  #   false
  # end
#only an option if task.user_id == current_user.id && only an option if the task status is pending

  def complete_task
    @task.update(status: "complete")
    redirect_to event_path(@task.event)
  end

  def remove_task
    @task.update(user: nil, status: "open")
    redirect_to event_path(@task.event)
  end

  private

  def task_params
    params.require(:task).permit(:title, :task_location, :description, :priority, :event_id, :location_id, :status)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1 class="panel-body card-info-head">Edit El Task</h1>
<br>
<%= bootstrap_form_for @task do |f| %>
<%= f.text_field :title, placeholder: "(Required)", class: "my-form-field ph", label_class: "feed"  %>
<br>
<br>
<%= f.text_field :task_location, label: "Start Location", placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed"  %>
<br>
<br>
<%= f.select :location_id, @task.event.locations.collect { |location| [location.name, location.id] }, {label: "End Location", label_class: "feed"}, {class: "my-form-field ph"}  %>
<br>
<br>
<%= f.text_area :description, placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed" %>
<br>
<br>
<%= f.select :priority, [1, 2, 3, 4, 5], {label: "Priority Level (1: High - 5 Low)", label_class: "feed"}, {class: "my-form-field ph"}  %>
<br>
<br>
<%= f.submit class: "btn btn-primary my-button"%>
<br>
<br>
<% end %>

app/views/tasks/new.html.erb
<h1 class="panel-body card-info-head">Create La New Task</h1>
<br>
<%= bootstrap_form_for @task do |f| %>
<%= f.text_field :title, placeholder: "(Required)", class: "my-form-field ph", label_class: "feed"  %>
<br>
<br>
<%= f.text_field :task_location, label: "Start Location", placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed"  %>
<br>
<br>
<%= f.select :location_id, @event.locations.collect { |location| [location.name, location.id] }, {label: "End Location", label_class: "feed"}, {class: "my-form-field ph"}  %>
<br>
<br>
<%= f.text_area :description, placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed" %>
<br>
<br>
<%= f.select :priority, [1, 2, 3, 4, 5], {label: "Priority Level (1: High - 5 Low)", label_class: "feed"}, {class: "my-form-field ph"}  %>
<br>
<br>
<%= f.hidden_field :event_id, value: params[:event_id] %>
<%= f.submit class: "btn btn-primary my-button"%>
<br>
<br>
<% end %>

app/views/tasks/show.html.erb
<h1 class="panel-body card-info-head">
  Task:
  <%= @task.title %>
  <%= link_to "Edit", edit_task_path(id: @task.id), class: "btn btn-primary my-button navbar-right" %>
  <%= button_to 'Delete', task_path(@task), method: :delete, class: "btn btn-primary my-button navbar-right" %>
</h1>

<div class="panel-body">
  <div class="panel-body card-info-body">
    <h3>Event:
      <%= link_to "#{@task.event.title}", event_path(id: @task.event.id) %></h3>
  </div>
  <br>

  <div class="panel-body card-info-body">
    <h3>Taskr:
      <%= @task.user.name if @task.user %></h3>
  </div>
  <br>

  <div class="panel-body card-info-body">
    <h3 >Status:
      <%= @task.status.capitalize %><%= link_to "+ Take Task", add_task_path(@task), class: "btn btn-primary my-button navbar-right" if @task.status == "open" %>
      <%= link_to "Finished Task", complete_task_path(@task), class: "btn btn-primary my-button navbar-right" if @task.user == current_user && @task.status == "in progress" %></h3>
      <%= link_to "- Drop Task", remove_task_path(@task), class: "btn btn-primary my-button navbar-right" if @task.user == current_user && @task.status == "in progress" %>
  </div>
  <br>

  <div class="panel-body card-info-body">
    <h3>Priority:
      <%= @task.priority %></h3>
  </div>
  <br>

  <div class="panel-body card-info-body">
    <h3>Start Location:
      <%= @task.task_location %></h3>
  </div>
  <br>

  <div class="panel-body card-info-body">
    <h3 >End Location (At Event):
      <%= @task.location.name %></h3>
  </div>
  <br>

  <div class="panel-body card-info-body">
    <h3>Description:
      <%= @task.description %></h3>
  </div>
  <br>
</div>