config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'application#home'

  get 'about/', to: 'application#about', as: 'about'
  
  resources :events

  resources :tasks, except: [:index]
  get '/add_task/:id', to: 'tasks#add_task', as: 'add_task'
  post '/add_task/:id', to: 'tasks#add_task'
  get '/complete_task/:id', to: 'tasks#complete_task', as: 'complete_task'
  post '/complete_task/:id', to: 'tasks#complete_task'
  get '/remove_task/:id', to: 'tasks#remove_task', as: 'remove_task'
  post '/remove_task/:id', to: 'tasks#remove_task'

  resources :users, except: [:index]

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  delete '/signout', to: 'sessions#destroy'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  manager         :boolean
#  password_digest :string
#  email           :string
#  phone           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_and_belongs_to_many :events
  has_many :tasks
  has_secure_password
  validates :email, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :already_signed_in, only: :new

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You Now Exist In This World"
      redirect_to user_path(@user)
    else
      flash[:error] = "Something Went Wrong - Existing Is Hard"
      render :new
    end
  end

  def show
    @events = []
    @user.tasks.each do |task|
      if !@events.include?(task.event)
        @events << task.event
      end
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "You Changed Yourself"
      redirect_to user_path(@user)
    else
      flash[:error] = "You Did Not Successfully Change Yourself"
      render :update
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:success] = "You Destroyed Yourself - As Only You Can"
    redirect_to root_path
  end



  private

  def user_params
    params.require(:user).permit(:name, :manager, :password, :password_confirmation, :email, :phone)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Sign Up</h1>
<%=bootstrap_form_for(@user) do |f|%>
  <div><%=f.text_field :name, placeholder: "Tony", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.text_field :email, placeholder: "Tony@tony.tony", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.password_field :password, placeholder: "@Dragons1 (Don\'t F'n Use This)", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.password_field :password_confirmation, placeholder: "Again! Again!", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.telephone_field :phone, placeholder: "123-456-7890", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.check_box :manager, class: "my-form-field ph", label_class: "feed"%></div>
<%=f.submit "Change Yo Self", class: "btn btn-primary my-button"%>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=bootstrap_form_for(@user) do |f|%>
  <div><%=f.text_field :name, placeholder: "Tony", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.text_field :email, placeholder: "Tony@tony.tony", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.password_field :password, placeholder: "@Dragons1 (Don\'t F'n Use This)", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.password_field :password_confirmation, placeholder: "Again! Again!", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.telephone_field :phone, placeholder: "123-456-7890", class: "my-form-field ph", label_class: "feed"%></div>
  <div><%=f.check_box :manager, class: "my-form-field ph", label_class: "feed"%></div>
<%=f.submit "Will Self Into Existence", class: "btn btn-primary my-button"%>
<% end %>

app/views/users/show.html.erb
<h1 class="panel-body card-info-head">
  Who Is You:
  <%= @user.name %><%= link_to "Edit Account", edit_user_path(id: @user.id), class: "btn btn-primary my-button navbar-right" %><%= button_to 'Delete Account', user_path(@user), method: :delete, class: "btn btn-primary my-button navbar-right" %></h1>
<div class="panel-body">
  <div class="panel-body card-info-body">
    <h3 >Email:
      <%= @user.email %></h3>
  </div>
  <br>
  <div class="panel-body card-info-body">
    <h3 >Phone:
      <%= @user.phone %></h3>
  </div>
  <br>
  <div class="panel-body card-info-body">
    <h3 >Is You A Manager:
      <%= @user.manager == true ? 'You Is Manager' : 'You Is Not Manager'%></h3>
  </div>
</div>
<br>
<div class="simple-calendar">

  <%= month_calendar events: @events do |date, event| %>
  <%= date.day %>
  <% event.each.with_index(1) do |e, i| %>
  <div>
    <%= "-"%>
    <%= link_to e.title, event_path(e) %>
  </div>
  <% end %>
  <% end %>
</div>