config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'application#home'

  get 'about/', to: 'application#about', as: 'about'
  
  resources :events

  resources :tasks, except: [:index]
  get '/add_task/:id', to: 'tasks#add_task', as: 'add_task'
  post '/add_task/:id', to: 'tasks#add_task'
  get '/complete_task/:id', to: 'tasks#complete_task', as: 'complete_task'
  post '/complete_task/:id', to: 'tasks#complete_task'
  get '/remove_task/:id', to: 'tasks#remove_task', as: 'remove_task'
  post '/remove_task/:id', to: 'tasks#remove_task'

  resources :users, except: [:index]

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  delete '/signout', to: 'sessions#destroy'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  title      :string
#  address    :string
#  start_date :datetime
#  end_date   :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Event < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tasks
  has_many :locations
  validates :start_date, presence: true
  validates :end_date, presence: true

  def start_time
    self.start_date
  end

  def end_time
    self.end_date
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in, except: [:index]
  before_action :admin, except: [:index, :show]
  before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.order("start_date")
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if params[:event][:locations]["locations"].empty?
      flash[:error] = "At Least One Location Is Required - So Do That!"
      render :new
    elsif
      @event.save
      flash[:success] = "Event Was Created - So That's Cool."
      redirect_to event_path(@event)
    else
      flash[:error] = "Event No Created - I Don't Why..."
      render :new
    end

    params[:event][:locations]["locations"].split(", ").each do |location|
      Location.create(name: location, event_id: @event.id)

    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Changes Applied - Solid."
      redirect_to event_path(@event)
    else
      flash[:error] = "So The Changes Couldn't Be Applied..."
      render :update
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event Destroyed - Do You Feel All Mighty And Powerful Now!?"
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :address, :start_date, :end_date, :locations)
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1 class="panel-body card-info-head">Edit Der New Event</h1>
<br>
<%= bootstrap_form_for @event do |f| %>
<%= f.text_field :title, placeholder: "(Required)", class: "my-form-field ph", label_class: "feed" %>
<br>
<%= f.text_field :address, placeholder: "(Optional) Street Address, City, State, Zip Code", class: "my-form-field ph", label_class: "feed"%>
<br>
<%= f.datetime_field :start_date, placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed" %>
<br>
<%= f.datetime_field :end_date, placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed" %>
<br>
  <%= f.fields_for :locations do |l| %>
    <%= l.text_area :locations, placeholder: "(Required) Enter locations separated by commas (i.e. green room, loading dock 1, ...)", class: "my-form-field ph", label_class: "feed" %>
  <% end %>
<br>
<%= f.submit class: "btn btn-primary my-button"%>
<br>
<% end %>

app/views/events/index.html.erb
<h1 class="panel-body card-info-head">Here We Find A List Of All Events - Just Amazing<%= link_to "+ New Event", new_event_path, class: "btn btn-primary my-button navbar-right" if admin %></h1>
<br>
<div class="row text-center">
  <% @events.each do |event| %>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <div class="caption">
        <h3 class="feed">
          <%= event.title %></h3>
        <h5 class="feed">Event Address:
          <%= event.address %></h5>
        <h5 class="feed">Start Date:
          <%= event.start_date.strftime("%A %B #{event.start_date.day.ordinalize}, %Y at %l:%M %p") %></h5>
        <h5 class="feed">End Date:
          <%= event.end_date.strftime("%A %B #{event.end_date.day.ordinalize}, %Y at %l:%M %p") %></h5>
        <p class="feed">
          <%= link_to "Details", event_path(event), class: "btn btn-primary my-button" %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 class="panel-body card-info-head">Create Der New Event</h1>
<br>
<%= bootstrap_form_for @event do |f| %>
<%= f.text_field :title, placeholder: "(Required)", class: "my-form-field ph", label_class: "feed" %>
<br>
<%= f.text_field :address, placeholder: "(Optional) Street Address, City, State, Zip Code", class: "my-form-field ph", label_class: "feed"%>
<br>
<%= f.datetime_field :start_date, placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed" %>
<br>
<%= f.datetime_field :end_date, placeholder: "(Optional)", class: "my-form-field ph", label_class: "feed" %>
<br>
  <%= f.fields_for :locations, label: "On-Site Locations" do |l| %>
    <%= l.text_area :locations, placeholder: "(Required) Enter locations separated by commas (i.e. green room, loading dock 1, ...)", class: "my-form-field ph", label_class: "feed" %>
  <% end %>
<br>
<%= f.submit class: "btn btn-primary my-button"%>
<br>
<% end %>

app/views/events/show.html.erb
<h1 class="panel-body card-info-head">
  <%= @event.title %>
  <%= link_to "Edit Event", edit_event_path(id: @event.id), class: "btn btn-primary my-button navbar-right" if admin %><%= button_to 'Delete Event', event_path(@event), method: :delete,class: "btn btn-primary my-button navbar-right" if admin %>
</h1>

<div class="panel-body">
  <div class="panel-body card-info-body">
    <h3 >Event Address:
      <%= @event.address %></h3>
  </div>
  <br>
  <div class="panel-body card-info-body">
    <h3>Event Start:
      <%= @event.start_date.strftime("%A %B #{@event.start_date.day.ordinalize}, %Y at %l:%M %p") %></h3>
    <h3>Event End:
      <%= @event.end_date.strftime("%A %B #{@event.end_date.day.ordinalize}, %Y at %l:%M %p") %></h3>
  </div>
  <br>
  <% if !@event.locations.nil? %>
  <div class="panel-body card-info-body">
    <h3>Locations:</h3>
    <ol>
      <% @event.locations.each do |location| %>
      <li><%= location.name %></li>
      <% end %>
    </ol>
    <% end %>
  </div>
  <br>
  <div class="panel-body card-info-body">
    <%= link_to "+ New Task", new_task_path(event_id: @event.id), class: "btn btn-primary my-button navbar-right" if admin %>
    <h3>Tasks:</h3>
    <p>&nbsp &nbsp Open:</p>
    <ol>
      <% @event.tasks.order("priority").each do |task| %>
        <% if task.status == "open" %>
        <li>
          <%= link_to "#{task.title} - Priority #{task.priority}", task_path(task) %></li>
        <% end %>
      <% end %>
    </ol>
    <br>
    <p>&nbsp &nbsp In Progress:
    </p>
    <ol>
      <% @event.tasks.order("priority").each do |task| %>
        <% if task.status == "in progress" %>
        <li><%= link_to "#{task.title} - Priority #{task.priority}", task_path(task) %></li>
        <% end %>
      <% end %>
    </ol>
    <br>
    <p>&nbsp &nbsp Complete:</p>
    <ol>
      <% @event.tasks.order("updated_at ").each do |task| %>
        <% if task.status == "complete" %>
        <li><%= link_to "#{task.title} - Finished on #{task.updated_at.strftime("%A %B #{@event.end_date.day.ordinalize}, %Y at %l:%M %p")}", task_path(task) %></li>
        <% end %>
      <% end %>
    </ol>
  </div>
</div>