config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'application#home'

  get 'about/', to: 'application#about', as: 'about'
  
  resources :events

  resources :tasks, except: [:index]
  get '/add_task/:id', to: 'tasks#add_task', as: 'add_task'
  post '/add_task/:id', to: 'tasks#add_task'
  get '/complete_task/:id', to: 'tasks#complete_task', as: 'complete_task'
  post '/complete_task/:id', to: 'tasks#complete_task'
  get '/remove_task/:id', to: 'tasks#remove_task', as: 'remove_task'
  post '/remove_task/:id', to: 'tasks#remove_task'

  resources :users, except: [:index]

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  delete '/signout', to: 'sessions#destroy'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>taskr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  </head>

  <body class="main">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
          <div>
            <a href="/" class="navbar-left"><img class="brenden" src=http://i.imgur.com/vLnUlUv.png></a>
             <div class="navbar-collapse collapse">
              <% if current_user %>
              <ul class="nav navbar-nav navbar-left">
                <li class="button"><%= link_to "About", about_path %></li>
                <li class="button"><%= link_to "Events", events_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "You-Me-I-Self", user_path(current_user) %></li>
                <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
              </ul>
              <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Sign In", signin_path %></li>
                <li><%= link_to "Sign Up", new_user_path %></li>
              </ul>
              <% end %>
          </div>
        </div>
      </div>
    </nav>


  <div class="container">


      <%= flash_messages %>


    <%= yield %>


  <!-- Footer -->
  <br>
  <footer>
    <div class="row text-center">
      <div class="col-lg-12">
        <p>&copy; 2017 taskr, Inc. 2017</p>
      </div>
    </div>
  </footer>
</div>

  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="js/bootstrap.min.js"></script>
  </body>

</html>